import type {
  TarotArchetypeId,
  TarotKnowledgeRelationKind,
  TarotKnowledgeSpreadContext,
  TarotReflectionStem,
  TarotReversedFacet,
  TarotSemanticProcess,
  TarotSemanticTag,
  TarotSemanticTagId,
  TarotSymbolicMotifId,
} from '../types';

const domainTags: readonly TarotSemanticTagId[] = [
  'decision',
  'emotion',
  'energy',
  'material',
  'money',
  'reflection',
  'relationship',
  'work',
];
const dynamicTags: readonly TarotSemanticTagId[] = [
  'action',
  'adaptation',
  'attachment',
  'change',
  'choice',
  'completion',
  'conflict',
  'connection',
  'growth',
  'momentum',
  'recovery',
  'release',
  'rest',
  'pause',
  'tempo',
  'transition',
  'integration',
];
const focusTags: readonly TarotSemanticTagId[] = [
  'boundaries',
  'clarity',
  'communication',
  'focus',
  'intuition',
  'learning',
  'opportunity',
  'planning',
  'resource',
  'risk',
  'support',
  'truth',
  'tradition',
  'uncertainty',
  'vision',
];
const qualityTags: readonly TarotSemanticTagId[] = [
  'balance',
  'courage',
  'creativity',
  'discipline',
  'freedom',
  'leadership',
  'patience',
  'reciprocity',
  'responsibility',
  'stability',
];

export const TAROT_SEMANTIC_TAGS: readonly TarotSemanticTag[] = [
  ...domainTags.map((id) => ({ group: 'domain' as const, id })),
  ...dynamicTags.map((id) => ({ group: 'dynamic' as const, id })),
  ...focusTags.map((id) => ({ group: 'focus' as const, id })),
  ...qualityTags.map((id) => ({ group: 'quality' as const, id })),
];

export const TAROT_KNOWLEDGE_SPREAD_CONTEXTS = [
  'day',
  'week',
  'month',
  'year',
  'love',
  'career',
  'money',
  'decision',
  'generic',
] as const satisfies readonly TarotKnowledgeSpreadContext[];

export const TAROT_REVERSED_FACETS = [
  'inner-expression',
  'blocked-energy',
  'unfinished-lesson',
  'overcompensation',
  'suppressed-potential',
  'delay',
  'reassessment',
  'false-certainty',
] as const satisfies readonly TarotReversedFacet[];

export const TAROT_KNOWLEDGE_RELATION_KINDS = [
  'reinforces',
  'contrasts',
  'softens',
  'intensifies',
  'balances',
  'redirects',
  'mirrors',
  'opens',
  'closes',
  'transforms',
] as const satisfies readonly TarotKnowledgeRelationKind[];

export const TAROT_ARCHETYPE_IDS = [
  'builder',
  'creator',
  'dreamer',
  'explorer',
  'guardian',
  'guide',
  'hermit',
  'leader',
  'mediator',
  'messenger',
  'protector',
  'reformer',
  'steward',
  'student',
  'visionary',
  'witness',
] as const satisfies readonly TarotArchetypeId[];

export const TAROT_SYMBOLIC_MOTIF_IDS = [
  'bridge',
  'circle',
  'crossroad',
  'door',
  'fire',
  'lantern',
  'mirror',
  'mountain',
  'river',
  'seed',
  'storm',
  'sunrise',
  'thread',
  'threshold',
  'well',
  'window',
] as const satisfies readonly TarotSymbolicMotifId[];

export const TAROT_SEMANTIC_PROCESSES = [
  'amplify',
  'balance',
  'begin',
  'build',
  'challenge',
  'choose',
  'communicate',
  'complete',
  'connect',
  'cultivate',
  'defer',
  'define',
  'direct',
  'discern',
  'endure',
  'examine',
  'expand',
  'focus',
  'ground',
  'illuminate',
  'imagine',
  'integrate',
  'internalize',
  'negotiate',
  'observe',
  'obstruct',
  'open',
  'overstate',
  'pause',
  'protect',
  'question',
  'recover',
  'release',
  'revisit',
  'revise',
  'share',
  'simplify',
  'suppress',
  'test',
  'transform',
  'verify',
] as const satisfies readonly TarotSemanticProcess[];

export const TAROT_REFLECTION_STEMS = [
  'what-already-changed',
  'what-needs-a-boundary',
  'what-needs-a-pause',
  'what-remains-unfinished',
  'what-support-is-nearby',
  'where-is-the-choice',
  'where-is-the-resistance',
  'which-step-is-testable',
] as const satisfies readonly TarotReflectionStem[];
