import type {
  NumerologyActiveValue,
  NumerologyArchetypeId,
  NumerologyKarmicValue,
  NumerologyKnowledgeRole,
  NumerologyMasterValue,
  NumerologyMotifId,
  NumerologyNarrativePurpose,
  NumerologySemanticProcess,
  NumerologySemanticTagId,
} from '../types';

export const NUMEROLOGY_ACTIVE_VALUES = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 22, 33,
] as const satisfies readonly NumerologyActiveValue[];
export const NUMEROLOGY_MASTER_VALUES = [
  11, 22, 33,
] as const satisfies readonly NumerologyMasterValue[];
export const NUMEROLOGY_KARMIC_VALUES = [
  13, 14, 16, 19,
] as const satisfies readonly NumerologyKarmicValue[];
export const NUMEROLOGY_KNOWLEDGE_ROLES = [
  'life-path',
  'birthday',
  'attitude',
  'personal-year',
  'personal-month',
  'personal-day',
] as const satisfies readonly NumerologyKnowledgeRole[];
export const NUMEROLOGY_ARCHETYPE_IDS = [
  'builder',
  'teacher',
  'visionary',
  'mediator',
  'explorer',
  'guardian',
  'creator',
  'analyst',
  'connector',
  'mentor',
] as const satisfies readonly NumerologyArchetypeId[];
export const NUMEROLOGY_MOTIF_IDS = [
  'spiral',
  'key',
  'tree',
  'compass-rose',
  'prism',
  'anchor-grid',
  'gatefold',
  'woven-path',
  'echo-ring',
  'ascending-steps',
  'open-hand',
  'calibration-mark',
] as const satisfies readonly NumerologyMotifId[];
export const NUMEROLOGY_NARRATIVE_PURPOSES = [
  'opening',
  'meaning',
  'challenge',
  'growth',
  'practice',
  'reflection',
  'closing',
] as const satisfies readonly NumerologyNarrativePurpose[];
export const NUMEROLOGY_SEMANTIC_TAGS = [
  'adaptation',
  'analysis',
  'authority',
  'autonomy',
  'balance',
  'boundaries',
  'care',
  'change',
  'clarity',
  'collaboration',
  'communication',
  'completion',
  'connection',
  'creativity',
  'decision',
  'discipline',
  'expression',
  'focus',
  'freedom',
  'growth',
  'influence',
  'initiative',
  'intuition',
  'learning',
  'manifestation',
  'mentoring',
  'movement',
  'observation',
  'opportunity',
  'patience',
  'planning',
  'practicality',
  'reciprocity',
  'reflection',
  'release',
  'resource',
  'responsibility',
  'service',
  'stability',
  'structure',
  'support',
  'transition',
  'trust',
  'truth',
  'uncertainty',
  'vision',
] as const satisfies readonly NumerologySemanticTagId[];
export const NUMEROLOGY_SEMANTIC_PROCESSES = [
  'analyze',
  'architect',
  'balance',
  'build',
  'clarify',
  'complete',
  'connect',
  'cultivate',
  'direct',
  'express',
  'explore',
  'focus',
  'ground',
  'illuminate',
  'initiate',
  'integrate',
  'mediate',
  'mentor',
  'observe',
  'organize',
  'question',
  'refine',
  'release',
  'sustain',
  'test',
  'translate',
] as const satisfies readonly NumerologySemanticProcess[];
