export const PILOT_CARD_IDS = [
  'major-fool',
  'major-magician',
  'major-high-priestess',
  'major-death',
  'major-tower',
  'major-star',
  'swords-three',
  'cups-ace',
];

export const PRODUCTION_VERSIONS = {
  artwork: 'premium-tarot-art-v1',
  edition: 'premium-rws-remastered',
  goldenMaster: 'premium-tarot-golden-master-v1',
  goldenReview: 'premium-tarot-golden-review-v1',
  goldenStyle: 'premium-tarot-style-v2',
  prompts: 'premium-tarot-prompts-v1',
  preparation: 'premium-tarot-preparation-v1',
  pilotPrompts: 'premium-tarot-pilot-prompts-v2',
  review: 'premium-tarot-review-v1',
  style: 'premium-tarot-style-v1',
};

const commonForbiddenChanges = [
  'Do not change the canonical subject count, poses, gestures, or spatial hierarchy.',
  'Do not add, remove, duplicate, mirror, or relocate divinatory symbols or suit objects.',
  'Do not bake a card frame, title, numeral, watermark, logo, or other text into the illustration.',
];

const major = [
  [
    'fool',
    0,
    'The Fool',
    'A young traveler steps lightly at a cliff edge, head lifted and posture open.',
    [
      'traveler at cliff edge',
      'small white dog',
      'white rose',
      'bundle on staff',
      'distant mountains',
      'bright sun',
    ],
    ['traveler', 'dog', 'rose', 'bundle', 'staff', 'cliff', 'mountains', 'sun'],
    'hopeful freedom and alert possibility',
  ],
  [
    'magician',
    1,
    'The Magician',
    'A standing ritual practitioner raises one hand toward heaven and points the other toward earth behind a table.',
    [
      'infinity sign',
      'raised wand',
      'one hand pointing downward',
      'table with wand, cup, sword, and pentacle',
      'red roses',
      'white lilies',
    ],
    ['magician', 'wand', 'cup', 'sword', 'pentacle', 'table', 'roses', 'lilies', 'infinity sign'],
    'focused agency and controlled potential',
  ],
  [
    'high-priestess',
    2,
    'The High Priestess',
    'A veiled priestess sits frontally between a black B pillar and a white J pillar.',
    [
      'black B pillar',
      'white J pillar',
      'crescent moon at her feet',
      'Torah scroll',
      'pomegranate veil',
      'blue robe',
      'lunar crown',
    ],
    ['priestess', 'two pillars', 'crescent moon', 'scroll', 'veil', 'pomegranates', 'crown'],
    'silent mystery and guarded knowledge',
  ],
  [
    'empress',
    3,
    'The Empress',
    'A crowned woman sits in a fertile landscape on a cushioned throne.',
    [
      'twelve-star crown',
      'wheat field',
      'forest and stream',
      'Venus shield',
      'patterned robe',
      'scepter',
    ],
    ['empress', 'throne', 'crown', 'wheat', 'forest', 'stream', 'Venus shield', 'scepter'],
    'abundance, warmth, and embodied creativity',
  ],
  [
    'emperor',
    4,
    'The Emperor',
    'A bearded ruler sits squarely on a stone throne decorated with ram heads.',
    [
      'ram-head throne',
      'red robes over armor',
      'ankh-shaped scepter',
      'golden orb',
      'barren mountains',
      'white beard',
    ],
    ['emperor', 'stone throne', 'ram heads', 'armor', 'red robe', 'scepter', 'orb', 'mountains'],
    'unyielding order and mature authority',
  ],
  [
    'hierophant',
    5,
    'The Hierophant',
    'A triple-crowned spiritual teacher sits between pillars and blesses two kneeling acolytes.',
    [
      'triple crown',
      'raised blessing hand',
      'two acolytes',
      'crossed keys',
      'two pillars',
      'triple cross staff',
    ],
    ['hierophant', 'two acolytes', 'crossed keys', 'pillars', 'triple crown', 'staff'],
    'ceremony, tradition, and transmission',
  ],
  [
    'lovers',
    6,
    'The Lovers',
    'A nude man and woman face one another beneath a radiant angel and sun.',
    [
      'angel Raphael',
      'radiant sun',
      'Tree of Knowledge with serpent',
      'flaming tree',
      'central mountain',
      'two nude figures',
    ],
    ['man', 'woman', 'angel', 'sun', 'serpent tree', 'flaming tree', 'mountain'],
    'sacred choice and vulnerable union',
  ],
  [
    'chariot',
    7,
    'The Chariot',
    'An armored charioteer stands beneath a starry canopy behind paired black and white sphinxes.',
    [
      'black sphinx',
      'white sphinx',
      'star canopy',
      'armored charioteer',
      'city behind',
      'wand',
      'square breastplate',
    ],
    ['charioteer', 'chariot', 'two sphinxes', 'star canopy', 'armor', 'wand', 'city'],
    'disciplined momentum and opposing forces held together',
  ],
  [
    'strength',
    8,
    'Strength',
    'A calm woman gently closes or holds open a lion’s jaws in a green landscape.',
    [
      'woman in white',
      'lion',
      'infinity sign',
      'flower garland',
      'distant mountain',
      'gentle hand position',
    ],
    ['woman', 'lion', 'flowers', 'infinity sign', 'mountain'],
    'compassionate courage and quiet mastery',
  ],
  [
    'hermit',
    9,
    'The Hermit',
    'An elderly cloaked figure stands alone on a snowy summit holding a lantern and staff.',
    [
      'six-pointed star inside lantern',
      'wooden staff',
      'grey cloak',
      'snowy peak',
      'elder profile',
    ],
    ['elder', 'lantern', 'star', 'staff', 'cloak', 'mountains'],
    'solitude, discernment, and inner guidance',
  ],
  [
    'wheel',
    10,
    'Wheel of Fortune',
    'A great esoteric wheel turns in the sky among clouds and four winged witnesses.',
    [
      'wheel with TARO letters and alchemical symbols',
      'sphinx atop wheel',
      'descending serpent',
      'ascending Anubis figure',
      'winged human, eagle, bull, and lion with books',
    ],
    ['wheel', 'sphinx', 'serpent', 'Anubis figure', 'human', 'eagle', 'bull', 'lion', 'four books'],
    'cosmic motion and consequential change',
  ],
  [
    'justice',
    11,
    'Justice',
    'A crowned figure sits frontally between pillars, holding an upright sword and balanced scales.',
    ['upright sword', 'balanced scales', 'red robe', 'square crown', 'two pillars', 'purple veil'],
    ['justice figure', 'sword', 'scales', 'crown', 'pillars', 'veil'],
    'clarity, balance, and sober consequence',
  ],
  [
    'hanged-man',
    12,
    'The Hanged Man',
    'A serene man hangs by one foot from a living T-shaped tree; the complete card remains canonically upright.',
    [
      'upright XII composition',
      'one foot bound to tree',
      'free leg bent across the other',
      'radiant halo',
      'blue tunic',
      'red leggings',
      'calm expression',
    ],
    ['hanging man', 'living tree', 'rope', 'halo', 'blue tunic', 'red leggings'],
    'voluntary suspension and illuminated surrender',
  ],
  [
    'death',
    13,
    'Death',
    'An armored skeleton rides a white horse through figures responding to irreversible transformation.',
    [
      'skeletal rider',
      'white horse',
      'black banner with white rose',
      'fallen crowned figure',
      'bishop',
      'child and maiden',
      'river and two towers',
      'sunrise on horizon',
    ],
    [
      'skeleton',
      'armor',
      'white horse',
      'black banner',
      'white rose',
      'fallen ruler',
      'bishop',
      'child',
      'maiden',
      'river',
      'towers',
      'sunrise',
    ],
    'solemn transformation with distant renewal',
  ],
  [
    'temperance',
    14,
    'Temperance',
    'A winged angel stands with one foot on land and one in water, pouring between two cups.',
    [
      'two cups with flowing water',
      'one foot on land and one in water',
      'triangle inside square',
      'path toward mountains',
      'rising sun or crown light',
      'irises',
    ],
    [
      'angel',
      'two cups',
      'water',
      'land',
      'triangle-square emblem',
      'path',
      'mountains',
      'sun',
      'irises',
    ],
    'harmonious flow and luminous patience',
  ],
  [
    'devil',
    15,
    'The Devil',
    'A horned winged figure presides over a loosely chained nude pair on a dark pedestal.',
    [
      'inverted pentagram',
      'horned winged figure',
      'raised and lowered hands',
      'torch',
      'male and female figures',
      'loose chains',
      'symbolic tails',
    ],
    ['devil figure', 'pentagram', 'pedestal', 'torch', 'two chained figures', 'chains', 'tails'],
    'shadowed attachment and confrontational self-knowledge',
  ],
  [
    'tower',
    16,
    'The Tower',
    'Lightning strikes a high stone tower, blasting away its crown as two figures fall.',
    [
      'lightning bolt',
      'crown torn from tower',
      'two falling figures',
      'flames from windows',
      'dark storm sky',
      'twenty-two fire sparks',
    ],
    ['tower', 'crown', 'lightning', 'two figures', 'flames', 'twenty-two sparks'],
    'violent revelation and destabilizing truth',
  ],
  [
    'star',
    17,
    'The Star',
    'A nude woman kneels with one foot on land and one on water while pouring two vessels.',
    [
      'one vessel pouring into pool',
      'one vessel pouring onto land in five streams',
      'large eight-pointed star',
      'seven smaller stars',
      'bird in tree',
      'open landscape',
    ],
    ['woman', 'two vessels', 'pool', 'five land streams', 'eight stars', 'tree', 'bird'],
    'quiet renewal, openness, and celestial hope',
  ],
  [
    'moon',
    18,
    'The Moon',
    'A winding path rises from water between a dog and wolf, then passes through two towers beneath the moon.',
    [
      'moon with face and layered phases',
      'two towers',
      'dog',
      'wolf',
      'crayfish emerging from water',
      'winding path',
      'descending light droplets',
    ],
    ['moon', 'two towers', 'dog', 'wolf', 'crayfish', 'water', 'path', 'light droplets'],
    'uncertainty, instinct, and dreamlike passage',
  ],
  [
    'sun',
    19,
    'The Sun',
    'A joyful child rides a white horse beneath a radiant sun, carrying a red banner.',
    [
      'large radiant sun with face',
      'child',
      'white horse',
      'red banner',
      'four sunflowers',
      'garden wall',
    ],
    ['sun', 'child', 'white horse', 'banner', 'four sunflowers', 'wall'],
    'unconcealed vitality and generous warmth',
  ],
  [
    'judgement',
    20,
    'Judgement',
    'The angel Gabriel sounds a trumpet above people rising from coffins toward the call.',
    [
      'angel with trumpet',
      'white banner with red cross',
      'rising adults and children',
      'open coffins',
      'water',
      'distant mountains',
    ],
    ['angel', 'trumpet', 'red-cross banner', 'rising figures', 'coffins', 'water', 'mountains'],
    'awakening, reckoning, and collective response',
  ],
  [
    'world',
    21,
    'The World',
    'A dancing central figure floats inside an oval laurel wreath, holding two wands.',
    [
      'oval laurel wreath',
      'two red infinity ribbons',
      'dancing central figure',
      'two wands',
      'human, eagle, bull, and lion in four corners',
    ],
    ['central figure', 'wreath', 'two ribbons', 'two wands', 'human', 'eagle', 'bull', 'lion'],
    'completion, integration, and expansive wholeness',
  ],
];

const minors = {
  wands: [
    [
      'ace',
      1,
      'Ace of Wands',
      'A hand emerges from a cloud holding one living, sprouting wand.',
      ['single sprouting wand', 'falling leaves', 'hand from cloud', 'castle', 'river and hills'],
      ['hand', 'cloud', 'one wand', 'leaves', 'castle', 'river', 'hills'],
      'ignition and raw creative force',
    ],
    [
      'two',
      2,
      'Two of Wands',
      'A robed figure on a battlement holds a globe and looks across sea and land.',
      [
        'globe in hand',
        'one held wand',
        'one fixed wand',
        'stone battlement',
        'ships and sea',
        'distant land',
      ],
      ['figure', 'globe', 'two wands', 'battlement', 'ships', 'sea'],
      'planning, possession, and distant possibility',
    ],
    [
      'three',
      3,
      'Three of Wands',
      'A red-cloaked figure stands with three wands overlooking ships on a broad sea.',
      ['three upright wands', 'figure seen from behind', 'red cloak', 'three ships', 'coastline'],
      ['figure', 'three wands', 'red cloak', 'ships', 'sea', 'coast'],
      'expectant expansion and outward vision',
    ],
    [
      'four',
      4,
      'Four of Wands',
      'Four upright wands form a floral threshold before celebrating people and a castle.',
      [
        'four wands',
        'fruit and flower garland',
        'two foreground celebrants',
        'gathering behind',
        'castle',
      ],
      ['four wands', 'garland', 'celebrants', 'castle'],
      'welcome, stability, and communal joy',
    ],
    [
      'five',
      5,
      'Five of Wands',
      'Five youths cross raised wands in a chaotic but nonlethal contest.',
      [
        'five youths',
        'five distinct wands',
        'varied tunics',
        'open ground',
        'conflicting diagonals',
      ],
      ['five youths', 'five wands', 'tunics'],
      'friction, practice, and competing intentions',
    ],
    [
      'six',
      6,
      'Six of Wands',
      'A laurel-crowned rider enters with attendants, holding a wand topped by a wreath.',
      [
        'mounted rider',
        'white or pale horse',
        'six wands total',
        'laurel crown',
        'victory wreath on wand',
        'attendant crowd',
      ],
      ['rider', 'horse', 'six wands', 'laurel crown', 'wreath', 'crowd'],
      'public recognition and composed victory',
    ],
    [
      'seven',
      7,
      'Seven of Wands',
      'A lone figure on high ground defends with one wand against six rising from below.',
      [
        'one defending figure',
        'one held wand',
        'six opposing wands',
        'high ground',
        'mismatched footwear',
      ],
      ['figure', 'seven wands', 'hill', 'mismatched shoes'],
      'pressure, resolve, and defended position',
    ],
    [
      'eight',
      8,
      'Eight of Wands',
      'Eight parallel wands fly diagonally across an open sky above river and fields.',
      [
        'exactly eight airborne wands',
        'diagonal motion',
        'open sky',
        'river',
        'distant settlement',
      ],
      ['eight wands', 'sky', 'river', 'fields', 'settlement'],
      'swift movement and unobstructed momentum',
    ],
    [
      'nine',
      9,
      'Nine of Wands',
      'A bandaged watchful figure grips one wand before a barrier of eight.',
      [
        'bandaged head',
        'one held wand',
        'eight upright background wands',
        'guarded posture',
        'distant hills',
      ],
      ['figure', 'bandage', 'nine wands', 'hills'],
      'wary endurance and maintained boundary',
    ],
    [
      'ten',
      10,
      'Ten of Wands',
      'A bent figure carries a dense bundle of ten wands toward a nearby town.',
      [
        'exactly ten bundled wands',
        'burdened figure',
        'obscured forward view',
        'town ahead',
        'worked earth',
      ],
      ['figure', 'ten wands', 'town', 'earth'],
      'heavy responsibility and determined completion',
    ],
    [
      'page',
      11,
      'Page of Wands',
      'A youthful messenger in a desert studies a tall sprouting wand.',
      [
        'single tall wand',
        'salamander-patterned tunic',
        'plumed hat',
        'three pyramids',
        'desert ground',
      ],
      ['page', 'wand', 'salamander tunic', 'hat', 'pyramids', 'desert'],
      'curiosity, announcement, and creative discovery',
    ],
    [
      'knight',
      12,
      'Knight of Wands',
      'An armored knight on a rearing horse carries a budding wand through a desert.',
      [
        'rearing horse',
        'armored knight',
        'single wand',
        'salamander cloak',
        'flame-like plume',
        'pyramids',
      ],
      ['knight', 'horse', 'armor', 'wand', 'salamander cloak', 'plume', 'pyramids'],
      'adventure, heat, and committed motion',
    ],
    [
      'queen',
      13,
      'Queen of Wands',
      'A confident queen sits with a wand and sunflower while a black cat waits before her.',
      ['queen on lion throne', 'single wand', 'sunflower', 'black cat', 'lion motifs', 'pyramids'],
      ['queen', 'throne', 'wand', 'sunflower', 'black cat', 'lions', 'pyramids'],
      'magnetic confidence and grounded warmth',
    ],
    [
      'king',
      14,
      'King of Wands',
      'A crowned king sits actively on a throne holding a living wand.',
      [
        'king with crown',
        'single sprouting wand',
        'salamander and lion throne motifs',
        'red-orange robes',
        'small salamander',
      ],
      ['king', 'throne', 'wand', 'crown', 'salamanders', 'lions'],
      'visionary leadership and mature fire',
    ],
  ],
  cups: [
    [
      'ace',
      1,
      'Ace of Cups',
      'A divine hand presents an overflowing chalice above a lotus-covered pool.',
      [
        'single ornate cup',
        'five streams of water',
        'dove descending with wafer',
        'hand from cloud',
        'lotus blossoms',
        'water droplets',
      ],
      ['hand', 'cloud', 'cup', 'five streams', 'dove', 'wafer', 'lotuses', 'pool'],
      'sacred abundance and emotional opening',
    ],
    [
      'two',
      2,
      'Two of Cups',
      'A man and woman exchange cups beneath a caduceus and winged lion head.',
      ['two people', 'two cups', 'caduceus', 'winged lion head', 'distant house and hills'],
      ['man', 'woman', 'two cups', 'caduceus', 'lion head', 'house'],
      'mutual recognition and balanced exchange',
    ],
    [
      'three',
      3,
      'Three of Cups',
      'Three women raise cups together in a circular harvest dance.',
      ['three women', 'three raised cups', 'fruit and pumpkins', 'flowers', 'circular dance'],
      ['three women', 'three cups', 'fruit', 'pumpkins', 'flowers'],
      'shared joy, friendship, and harvest',
    ],
    [
      'four',
      4,
      'Four of Cups',
      'A seated figure under a tree studies or ignores a fourth cup offered from a cloud.',
      [
        'seated cross-armed figure',
        'tree',
        'three cups on ground',
        'fourth cup from cloud',
        'green landscape',
      ],
      ['figure', 'tree', 'four cups', 'cloud', 'landscape'],
      'withdrawal, contemplation, and unseen offer',
    ],
    [
      'five',
      5,
      'Five of Cups',
      'A cloaked figure mourns three spilled cups while two remain standing behind.',
      [
        'black cloaked figure',
        'three spilled cups',
        'two upright cups',
        'river',
        'bridge',
        'distant building',
      ],
      ['figure', 'cloak', 'five cups', 'river', 'bridge', 'building'],
      'grief, partial loss, and remaining support',
    ],
    [
      'six',
      6,
      'Six of Cups',
      'One child offers another a flower-filled cup in an old village courtyard.',
      [
        'two children',
        'six cups total',
        'white flowers in cups',
        'village buildings',
        'guarded adult in distance',
      ],
      ['two children', 'six cups', 'white flowers', 'village', 'adult'],
      'memory, innocence, and generous familiarity',
    ],
    [
      'seven',
      7,
      'Seven of Cups',
      'A silhouetted figure confronts seven cloud-borne cups containing distinct visions.',
      [
        'seven cups',
        'castle',
        'jewels',
        'laurel wreath',
        'dragon',
        'veiled figure',
        'snake',
        'human head',
      ],
      [
        'silhouette',
        'seven cups',
        'cloud',
        'castle',
        'jewels',
        'wreath',
        'dragon',
        'veiled figure',
        'snake',
        'head',
      ],
      'possibility, projection, and seductive imagination',
    ],
    [
      'eight',
      8,
      'Eight of Cups',
      'A cloaked traveler walks away from eight stacked cups toward mountains under an eclipsed moon.',
      [
        'eight cups in deliberate gap arrangement',
        'departing cloaked figure',
        'staff',
        'mountains',
        'river',
        'moon and sun overlap',
      ],
      ['traveler', 'cloak', 'staff', 'eight cups', 'mountains', 'river', 'moon'],
      'chosen departure and deeper search',
    ],
    [
      'nine',
      9,
      'Nine of Cups',
      'A satisfied seated figure poses before a curved display of nine cups.',
      ['seated figure', 'crossed arms', 'nine cups', 'curved blue-draped table', 'red cap'],
      ['figure', 'chair', 'nine cups', 'table', 'blue cloth', 'red cap'],
      'contentment, pride, and fulfilled appetite',
    ],
    [
      'ten',
      10,
      'Ten of Cups',
      'A couple raises their arms beneath a rainbow of ten cups as children play near home.',
      ['rainbow', 'ten cups', 'two adults', 'two children', 'home', 'river and trees'],
      ['rainbow', 'ten cups', 'couple', 'two children', 'home', 'river', 'trees'],
      'belonging, emotional completion, and shared home',
    ],
    [
      'page',
      11,
      'Page of Cups',
      'A youthful page holds a cup from which a fish unexpectedly appears beside the sea.',
      [
        'page',
        'single cup',
        'fish emerging from cup',
        'blue floral tunic',
        'beret and scarf',
        'rolling sea',
      ],
      ['page', 'cup', 'fish', 'floral tunic', 'hat', 'sea'],
      'surprise, sensitivity, and imaginative message',
    ],
    [
      'knight',
      12,
      'Knight of Cups',
      'An armored knight calmly rides a white horse while presenting a cup.',
      [
        'armored knight',
        'white horse',
        'single cup',
        'winged helmet',
        'river',
        'distant mountains',
      ],
      ['knight', 'armor', 'white horse', 'cup', 'winged helmet', 'river', 'mountains'],
      'romantic offering and measured pursuit',
    ],
    [
      'queen',
      13,
      'Queen of Cups',
      'A queen on a shoreline throne contemplates an elaborate closed cup.',
      [
        'queen',
        'shoreline throne',
        'ornate lidded cup',
        'cherub carvings',
        'pebbles',
        'sea cliffs',
      ],
      ['queen', 'throne', 'closed cup', 'cherubs', 'pebbles', 'sea'],
      'deep receptivity and protected feeling',
    ],
    [
      'king',
      14,
      'King of Cups',
      'A king sits on a stone throne amid a moving sea holding cup and scepter.',
      ['king', 'stone throne in water', 'single cup', 'scepter', 'ship', 'leaping fish'],
      ['king', 'throne', 'cup', 'scepter', 'sea', 'ship', 'fish'],
      'emotional command amid changing conditions',
    ],
  ],
  swords: [
    [
      'ace',
      1,
      'Ace of Swords',
      'A hand from a cloud raises a single upright sword crowned by a wreath.',
      [
        'one upright sword',
        'gold crown',
        'laurel and palm wreath',
        'falling yod shapes',
        'distant mountains',
      ],
      ['hand', 'cloud', 'sword', 'crown', 'wreath', 'yods', 'mountains'],
      'piercing clarity and decisive truth',
    ],
    [
      'two',
      2,
      'Two of Swords',
      'A blindfolded seated woman crosses two swords before a rocky moonlit sea.',
      [
        'blindfolded woman',
        'two crossed swords',
        'stone seat',
        'crescent moon',
        'rocky islands',
        'calm sea',
      ],
      ['woman', 'blindfold', 'two swords', 'seat', 'moon', 'rocks', 'sea'],
      'stalemate, guarded balance, and suspended decision',
    ],
    [
      'three',
      3,
      'Three of Swords',
      'A red heart is pierced by three swords against rain-heavy clouds.',
      ['single red heart', 'exactly three piercing swords', 'rain', 'grey storm clouds'],
      ['heart', 'three swords', 'rain', 'clouds'],
      'direct sorrow and painful clarity',
    ],
    [
      'four',
      4,
      'Four of Swords',
      'A recumbent knight rests on a church tomb beneath three swords, with one carved below.',
      [
        'recumbent effigy',
        'three wall swords',
        'one horizontal sword',
        'stained-glass window',
        'praying hands',
      ],
      ['knight effigy', 'four swords', 'tomb', 'stained glass', 'church wall'],
      'rest, sanctuary, and deliberate recovery',
    ],
    [
      'five',
      5,
      'Five of Swords',
      'A smirking figure gathers swords while two defeated people walk toward a troubled shore.',
      ['three figures', 'five swords total', 'two swords on ground', 'jagged clouds', 'water'],
      ['three figures', 'five swords', 'clouds', 'shore', 'water'],
      'hollow victory, conflict, and consequence',
    ],
    [
      'six',
      6,
      'Six of Swords',
      'A ferryman carries a cloaked adult and child across water in a boat holding six swords.',
      [
        'boat',
        'ferryman with pole',
        'cloaked adult',
        'child',
        'six upright swords in boat',
        'rough and calm water',
      ],
      ['boat', 'ferryman', 'adult', 'child', 'six swords', 'water'],
      'passage, transition, and carried sorrow',
    ],
    [
      'seven',
      7,
      'Seven of Swords',
      'A figure stealthily carries five swords away from a camp while two remain planted.',
      [
        'one departing figure',
        'five carried swords',
        'two upright swords left behind',
        'tents',
        'distant people',
      ],
      ['figure', 'seven swords', 'tents', 'camp'],
      'strategy, evasion, and incomplete escape',
    ],
    [
      'eight',
      8,
      'Eight of Swords',
      'A blindfolded bound woman stands amid eight swords on wet ground below a castle.',
      ['blindfolded woman', 'loose bindings', 'eight swords', 'mud and water', 'distant castle'],
      ['woman', 'blindfold', 'bindings', 'eight swords', 'water', 'castle'],
      'restriction, fear, and a narrow path outward',
    ],
    [
      'nine',
      9,
      'Nine of Swords',
      'A person sits upright in bed covering their face beneath nine horizontal swords.',
      [
        'distressed seated person',
        'bed',
        'nine wall swords',
        'carved bed frame',
        'astrological quilt',
      ],
      ['person', 'bed', 'nine swords', 'quilt', 'carved frame'],
      'night anxiety, grief, and mental pressure',
    ],
    [
      'ten',
      10,
      'Ten of Swords',
      'A prone figure lies beneath ten swords as dawn breaks beyond dark water.',
      [
        'prone figure',
        'ten swords',
        'black sky',
        'golden sunrise',
        'calm water',
        'distant mountains',
      ],
      ['figure', 'ten swords', 'dark sky', 'sunrise', 'water', 'mountains'],
      'total ending with unavoidable dawn',
    ],
    [
      'page',
      11,
      'Page of Swords',
      'A windswept youth stands on uneven ground holding an upright sword in both hands.',
      [
        'youth',
        'single sword',
        'windblown hair and tunic',
        'dramatic clouds',
        'circling birds',
        'distant trees',
      ],
      ['page', 'sword', 'clouds', 'birds', 'trees', 'hill'],
      'alert curiosity and restless intellect',
    ],
    [
      'knight',
      12,
      'Knight of Swords',
      'An armored knight charges on a white horse with sword raised into a storm.',
      [
        'charging white horse',
        'armored knight',
        'raised sword',
        'wind-torn clouds',
        'bent trees',
        'butterfly and bird motifs',
      ],
      ['knight', 'white horse', 'armor', 'sword', 'clouds', 'trees'],
      'forceful pursuit and sharpened momentum',
    ],
    [
      'queen',
      13,
      'Queen of Swords',
      'A crowned queen sits in profile with sword upright and her free hand extended.',
      [
        'queen in profile',
        'upright sword',
        'extended open hand',
        'butterfly crown and throne motifs',
        'clouds',
        'single bird',
      ],
      ['queen', 'throne', 'sword', 'crown', 'butterflies', 'clouds', 'bird'],
      'discernment, independence, and honest welcome',
    ],
    [
      'king',
      14,
      'King of Swords',
      'A frontal king holds an upright sword on a throne beneath a clearing sky.',
      [
        'king facing forward',
        'upright sword',
        'butterfly throne carvings',
        'blue robe and purple cloak',
        'trees',
        'two birds',
      ],
      ['king', 'throne', 'sword', 'butterflies', 'trees', 'two birds'],
      'ethical authority and intellectual command',
    ],
  ],
  pentacles: [
    [
      'ace',
      1,
      'Ace of Pentacles',
      'A hand from a cloud offers one golden pentacle above a flowering garden path.',
      [
        'single pentacle',
        'hand from cloud',
        'garden lilies and roses',
        'hedge arch',
        'path',
        'distant mountain',
      ],
      ['hand', 'cloud', 'pentacle', 'garden', 'arch', 'path', 'mountain'],
      'material opportunity and grounded beginning',
    ],
    [
      'two',
      2,
      'Two of Pentacles',
      'A dancer juggles two pentacles joined by an infinity ribbon while ships ride high waves.',
      [
        'two pentacles',
        'green infinity ribbon',
        'juggling figure',
        'two ships',
        'rolling waves',
        'tall red hat',
      ],
      ['figure', 'two pentacles', 'infinity ribbon', 'ships', 'waves', 'hat'],
      'adaptation, rhythm, and moving balance',
    ],
    [
      'three',
      3,
      'Three of Pentacles',
      'An artisan stands on a bench in a cathedral speaking with two patrons beneath a carved arch.',
      [
        'artisan',
        'two patrons',
        'three pentacles in arch',
        'cathedral stonework',
        'bench',
        'plan or document',
      ],
      ['three figures', 'three pentacles', 'cathedral', 'bench', 'document'],
      'craft, collaboration, and visible skill',
    ],
    [
      'four',
      4,
      'Four of Pentacles',
      'A crowned seated figure grips one pentacle while balancing another and pinning two below.',
      [
        'four pentacles',
        'one on crown',
        'one held to chest',
        'two beneath feet',
        'seated figure',
        'city behind',
      ],
      ['figure', 'crown', 'four pentacles', 'seat', 'city'],
      'control, security, and constricted holding',
    ],
    [
      'five',
      5,
      'Five of Pentacles',
      'Two impoverished figures cross snow outside a glowing stained-glass window of five pentacles.',
      [
        'two struggling figures',
        'snowstorm',
        'five pentacles in stained glass',
        'crutches',
        'bare feet',
        'lit window',
      ],
      ['two figures', 'crutches', 'snow', 'five pentacles', 'stained-glass window'],
      'hardship, exclusion, and nearby shelter',
    ],
    [
      'six',
      6,
      'Six of Pentacles',
      'A wealthy merchant uses scales while giving coins to two kneeling people.',
      [
        'standing merchant',
        'two kneeling recipients',
        'balanced scales',
        'six pentacles',
        'coins being distributed',
        'town setting',
      ],
      ['merchant', 'two recipients', 'scales', 'six pentacles', 'coins', 'town'],
      'exchange, power, and measured generosity',
    ],
    [
      'seven',
      7,
      'Seven of Pentacles',
      'A tired farmer leans on a hoe and studies seven pentacles growing on a vine.',
      ['farmer', 'hoe', 'seven pentacles', 'leafy vine', 'worked soil', 'patient posture'],
      ['farmer', 'hoe', 'seven pentacles', 'vine', 'soil'],
      'assessment, cultivation, and delayed return',
    ],
    [
      'eight',
      8,
      'Eight of Pentacles',
      'A seated craftsperson hammers a pentacle while seven finished coins are displayed nearby.',
      ['craftsperson', 'hammer and chisel', 'eight pentacles', 'work bench', 'distant town'],
      ['craftsperson', 'tools', 'eight pentacles', 'bench', 'town'],
      'apprenticeship, repetition, and practiced mastery',
    ],
    [
      'nine',
      9,
      'Nine of Pentacles',
      'A richly robed woman stands in a vineyard with a hooded falcon.',
      [
        'woman in patterned robe',
        'nine pentacles',
        'grapevines',
        'hooded falcon',
        'snail',
        'estate',
      ],
      ['woman', 'nine pentacles', 'grapes', 'falcon', 'snail', 'estate'],
      'self-possession, refinement, and earned abundance',
    ],
    [
      'ten',
      10,
      'Ten of Pentacles',
      'An elder sits with dogs beneath an arch as a family gathers in a prosperous courtyard.',
      [
        'elder',
        'two dogs',
        'adult couple and child',
        'ten pentacles in Tree-of-Life arrangement',
        'stone arch',
        'family estate',
      ],
      ['elder', 'two dogs', 'couple', 'child', 'ten pentacles', 'arch', 'estate'],
      'legacy, continuity, and material belonging',
    ],
    [
      'page',
      11,
      'Page of Pentacles',
      'A youthful page studies one pentacle held carefully against a fertile landscape.',
      ['page', 'single pentacle', 'green field', 'flowers', 'plowed field', 'distant mountains'],
      ['page', 'pentacle', 'field', 'flowers', 'mountains'],
      'study, diligence, and practical promise',
    ],
    [
      'knight',
      12,
      'Knight of Pentacles',
      'An armored knight sits on a stationary dark horse presenting one pentacle over worked fields.',
      [
        'armored knight',
        'stationary black horse',
        'single pentacle',
        'plowed fields',
        'oak leaves',
        'distant hills',
      ],
      ['knight', 'armor', 'dark horse', 'pentacle', 'fields', 'hills'],
      'reliability, patience, and sustained work',
    ],
    [
      'queen',
      13,
      'Queen of Pentacles',
      'A queen sits in a lush garden contemplating one pentacle in her lap.',
      [
        'queen',
        'carved throne',
        'single pentacle',
        'rabbit',
        'roses',
        'fruitful landscape',
        'mountains',
      ],
      ['queen', 'throne', 'pentacle', 'rabbit', 'roses', 'landscape', 'mountains'],
      'nurturing competence and embodied prosperity',
    ],
    [
      'king',
      14,
      'King of Pentacles',
      'A richly dressed king sits on a bull-carved throne amid vines, holding pentacle and scepter.',
      [
        'king',
        'bull-carved throne',
        'single pentacle',
        'scepter',
        'grapevines',
        'castle',
        'golden crown',
      ],
      ['king', 'throne', 'bulls', 'pentacle', 'scepter', 'grapes', 'castle', 'crown'],
      'stewardship, stability, and mature material power',
    ],
  ],
};

const rankNames = [
  'ace',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'page',
  'knight',
  'queen',
  'king',
];

function referencePath(cardId, number, suit) {
  if (!suit) {
    const slug = cardId.slice('major-'.length);
    return `src/assets/tarot/cards/rws/major/${String(number).padStart(2, '0')}-${slug}.jpg`;
  }
  return `src/assets/tarot/cards/rws/${suit}/${rankNames[number - 1]}-${suit}.jpg`;
}

function compositionReference(description, tone, referenceAsset, arcana) {
  return {
    background:
      'Preserve the canonical distant landscape, architecture, weather, and celestial elements.',
    emotionalTone: tone,
    foreground: 'Keep every canonical near-field figure, object, and suit symbol unobscured.',
    framing:
      'Portrait 7:12 illustration-only composition with safe edges and no baked card frame or typography.',
    mainSubject: description.split('.')[0],
    midground: description,
    poseAndComposition: description,
    referenceAsset,
    referenceRule:
      arcana === 'major'
        ? 'Use the normalized RWS card only to verify semantic composition and symbol placement.'
        : 'Use the normalized RWS card to verify figure action, exact suit-object count, and spatial hierarchy.',
  };
}

function createEntry({
  arcana,
  canonicalName,
  description,
  id,
  number,
  objects,
  suit,
  symbols,
  tone,
}) {
  const referenceAsset = referencePath(id, number, suit);
  const rank = suit ? rankNames[number - 1] : undefined;
  const isGoldenMaster = id === 'major-fool';
  const goldenMasterComposition = {
    background:
      'Distant mountains recede through clear high-altitude haze beneath a bright sun and expansive blue sky.',
    emotionalTone:
      'Luminous, adventurous, optimistic, free, slightly dangerous, elevated, and alive',
    foreground:
      'The small white dog, white rose and hand relationship where natural, and tactile cliff-edge detail establish the nearest plane.',
    framing:
      'Portrait 7:12 illustration-only composition with open sky, breathable edges, and safe placement for every primary symbol; no typography or frame.',
    mainSubject:
      'A naturally proportioned young traveler moves with confident openness and curiosity at a high cliff edge, subtly unaware of the danger',
    midground:
      'The traveler occupies a distinct subject plane while the path, cliff terrain, and supporting landscape overlap into the distance.',
    poseAndComposition:
      'Preserve the recognizable symbolic relationship and narrative role while allowing naturalistic pose refinement, cinematic depth, perspective, and lighting.',
    referenceAsset,
    referenceRule:
      'Use the normalized RWS card only as a semantic identity reference; do not reconstruct its pixels or rigidly trace its pose.',
  };
  return {
    arcana,
    canonicalName,
    cardId: id,
    ...(suit ? { rank, suit } : {}),
    productionStatus: PILOT_CARD_IDS.includes(id) ? 'prompt-ready' : 'pending',
    reviewStatus: 'not-reviewed',
    sourceReferenceId: `rws-public-domain-v1:${id}`,
    promptId: `${PRODUCTION_VERSIONS.prompts}:${id}`,
    styleVersion: isGoldenMaster ? PRODUCTION_VERSIONS.goldenStyle : PRODUCTION_VERSIONS.style,
    compositionReference: isGoldenMaster
      ? goldenMasterComposition
      : compositionReference(description, tone, referenceAsset, arcana),
    symbolismChecklist: symbols,
    requiredObjects: objects,
    forbiddenChanges: isGoldenMaster
      ? [
          'Do not remove, duplicate, mirror, or make ambiguous any of the six primary symbols.',
          'Do not rigidly trace or reconstruct the classic scan; preserve semantic identity while refining pose and perspective naturally.',
          'Do not bake a card frame, title, numeral, watermark, logo, or other text into the illustration.',
          'Do not replace luminous optimism and slight danger with generic dark-fantasy gloom.',
        ]
      : [
          ...commonForbiddenChanges,
          `Do not weaken or replace the card-specific emotional identity: ${tone}.`,
        ],
    paletteFamily: suit ?? 'major',
    lightingFamily: suit ? `${suit}-cinematic` : 'major-symbolic',
    depthFamily:
      arcana === 'major' ? 'ceremonial-depth' : number >= 11 ? 'court-depth' : 'narrative-depth',
    outputPath: `premium-production/candidates/${id}-v1.jpg`,
    isGoldenMaster,
    ...(isGoldenMaster
      ? {
          goldenMasterStatus: 'not-started',
          goldenMasterVersion: PRODUCTION_VERSIONS.goldenMaster,
          goldenMasterCandidateVersion: 1,
          goldenMasterStyleVersion: PRODUCTION_VERSIONS.goldenStyle,
          goldenMasterReviewStatus: 'not-reviewed',
        }
      : {}),
    version: 1,
  };
}

export const productionCards = [
  ...major.map(([slug, number, canonicalName, description, symbols, objects, tone]) =>
    createEntry({
      arcana: 'major',
      canonicalName,
      description,
      id: `major-${slug}`,
      number,
      objects,
      symbols,
      tone,
    }),
  ),
  ...Object.entries(minors).flatMap(([suit, cards]) =>
    cards.map(([rank, number, canonicalName, description, symbols, objects, tone]) =>
      createEntry({
        arcana: 'minor',
        canonicalName,
        description,
        id: `${suit}-${rank}`,
        number,
        objects,
        suit,
        symbols,
        tone,
      }),
    ),
  ),
];
